### ISSUE TITLE
Realize notifications about tasks

### ISSUE THREAD

**Issue by labi-le** [labi-le/control-panel#6]

**Comment by labi-le** [comment]
wtf Danya?

**Comment by ddurov** [comment]
upd.
integrate tasks viewer and notifications with different styles (spinner loader in tasks viewer)

**Comment by ddurov** [comment]
done
![image](https://user-images.githubusercontent.com/76112338/155857289-71f35607-1708-4f17-9f76-9720051cc18b.png)
![image](https://user-images.githubusercontent.com/76112338/155857301-0d9d92a1-16bf-4668-9a0a-891f334fbd96.png)
